[tool.poetry]
name = "vocode"
version = "0.1.42"
description = "The all-in-one voice SDK"
authors = ["Ajay Raj <ajay@vocode.dev>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "1.10.5"
python-dotenv = "0.21.1"
typing-extensions = "4.5.0"
websockets = "10.4"
anyio = "3.6.2"
certifi = "2022.12.7"
cffi = "1.15.1"
charset-normalizer = "3.0.1"
click = "8.1.3"
decorator = "5.1.1"
fastapi = "0.92.0"
h11 = "0.14.0"
idna = "3.4"
numpy = "1.24.2"
ply = "3.11"
pycparser = "2.21"
requests = "2.28.2"
six = "1.16.0"
sniffio = "1.3.0"
sounddevice = "0.4.6"
starlette = "0.25.0"
urllib3 = "1.26.14"
uvicorn = "0.20.0"
black = "23.1.0"
flake8 = "6.0.0"
mccabe = "0.7.0"
mypy-extensions = "1.0.0"
packaging = "23.0"
pathspec = "0.11.0"
platformdirs = "3.1.0"
pyaudio = "0.2.13"
pycodestyle = "2.10.0"
pyflakes = "3.0.1"
pyjwt = "2.6.0"
python-multipart = "0.0.6"
pytz = "2022.7.1"
tomli = "2.0.1"
twilio = "7.16.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
