[tool.poetry]
name = "vocode"
version = "0.1.9"
description = "The all-in-one voice SDK"
authors = ["Ajay Raj <ajay@vocode.dev>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pyaudio = "0.2.13"
pydantic = "1.10.5"
python-dotenv = "0.21.1"
typing-extensions = "4.5.0"
websockets = "10.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
