[tool.poetry]
name = "vocode"
version = "0.1.107"
description = "The all-in-one voice SDK"
authors = ["Ajay Raj <ajay@vocode.dev>"]
license = "MIT License"
readme = "README.md"
homepage = "https://github.com/vocodedev/vocode-python"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.11"
pydub = "^0.25.1"
nltk = "^3.8.1"
langchain = "^0.0.149"
openai = "^0.27.4"
sounddevice = "^0.4.6"
azure-cognitiveservices-speech = "^1.27.0"
websockets = "^11.0.2"
requests = "^2.28.2"
uvicorn = "^0.21.1"
fastapi = "^0.95.1"
jinja2 = "^3.1.2"
python-multipart = "^0.0.6"
six = "^1.16.0"

elevenlabs = {version = "^0.2.6", optional = true}
google-cloud-texttospeech = {version = "^2.14.1", optional = true}
gtts = {version = "^2.3.1", optional = true}

google-cloud-speech = {version = "^2.19.0", optional = true}

redis = {version = "^4.5.4", optional = true}
twilio = {version = "^8.1.0", optional = true}

anthropic = {version = "^0.2.7", optional = true}

[tool.poetry.extras]
synthesizers = ["gtts", "google-cloud-texttospeech", "elevenlabs"]
transcribers = ["google-cloud-speech"]
telephony = ["twilio", "redis"]
agents = ["anthropic"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
