[tool.poetry]
name = "vocode"
version = "0.1.101"
description = "The all-in-one voice SDK"
authors = ["Ajay Raj <ajay@vocode.dev>"]
license = "MIT License"
readme = "README.md"
homepage = "https://github.com/vocodedev/vocode-python"

[tool.poetry.dependencies]
python = "^3.8.1"
pydantic = ">=1.9.0"
python-dotenv = ">=0.21.1"
typing-extensions = ">=3.10.0.2"
websockets = "10.4"
anyio = "3.6.2"
certifi = "2022.12.7"
cffi = "1.15.1"
charset-normalizer = "3.0.1"
click = "8.1.3"
decorator = "5.1.1"
fastapi = "0.92.0"
h11 = "0.14.0"
idna = "3.4"
numpy = "1.24.2"
ply = "3.11"
pycparser = "2.21"
requests = "2.28.2"
six = "1.16.0"
sniffio = "1.3.0"
sounddevice = { version = "0.4.6", optional = true }
starlette = "0.25.0"
urllib3 = "1.26.14"
uvicorn = "0.20.0"
mccabe = "0.7.0"
mypy-extensions = "1.0.0"
packaging = "23.0"
pathspec = "0.11.0"
platformdirs = "3.1.0"
pyaudio = { version = "0.2.13", optional = true }
pycodestyle = "2.10.0"
pyflakes = ">=2.5.0"
pyjwt = "2.6.0"
python-multipart = "0.0.6"
pytz = "2022.7.1"
tomli = "2.0.1"
aiohttp = "3.8.4"
aiosignal = "1.3.1"
async-timeout = "4.0.2"
attrs = "22.2.0"
azure-cognitiveservices-speech = "1.25.0"
dataclasses-json = "0.5.7"
frozenlist = "1.3.3"
langchain = "^0.0.146"
marshmallow = "3.19.0"
marshmallow-enum = "1.5.1"
multidict = "6.0.4"
openai = "0.27.2"
pydub = { version = "0.25.1", optional = true }
pyyaml = "6.0"
sqlalchemy = "1.4.47"
tenacity = "8.2.2"
tqdm = "4.65.0"
typing-inspect = "0.8.0"
yarl = "1.8.2"
cachetools = "5.3.0"
google-api-core = "2.11.0"
google-auth = "2.16.3"
google-cloud-speech = "2.17.3"
google-cloud-texttospeech = "2.14.1"
googleapis-common-protos = "1.59.0"
grpcio = ">=1.47.0"
grpcio-status = ">=1.47.0"
jinja2 = "3.1.2"
joblib = "1.2.0"
markupsafe = "2.1.2"
nltk = "3.8.1"
proto-plus = "1.22.2"
protobuf = ">=3.20.3"
pyasn1 = "0.4.8"
pyasn1-modules = "0.2.8"
redis = "4.5.3"
regex = "2023.3.23"
rsa = "4.9"
twilio = "7.17.0"
gtts = "2.3.1"

[tool.poetry.extras]
io = ["pyaudio", "sounddevice", "pydub"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
